site_name: Eirbware's Docs
site_url: https://docs.eirb.fr
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Gestion du VPS:
    - gestion_vps/intro.md
    - gestion_vps/installation.md
    - gestion_vps/sudo.md
    - gestion_vps/docker.md
    - gestion_vps/nginx.md
    - gestion_vps/services.md
    - gestion_vps/redirections.md
    - gestion_vps/users.md
    - gestion_vps/firewall.md
    - gestion_vps/ssh.md
    - gestion_vps/vpn.md
    - gestion_vps/monitoring.md
  - Passation: passation.md
  - Github: github.md
  - Eirbuntu: eirbuntu.md
  - HOWTO respo web:
    - respo_web/intro.md
    - respo_web/ajout_site.md
    - respo_web/acces_site.md
    - respo_web/acces_vpn.md
    - respo_web/maj_site.md
    - respo_web/connexion_cas.md
    - respo_web/conseils.md

  - About: about.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - content.code.copy
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference



# Images https://squidfunk.github.io/mkdocs-material/reference/images/?h=image
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - toc:
      permalink: ¶

  # Enables emojis, required for tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true

  # - glightbox
